name: UnicornStoreWeb
options:
  bundleIdPrefix: com.hellodajidali
  deploymentTarget:
    iOS: "14.0"

settings:
  base:
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: "1.0.0"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: ""
    PROVISIONING_PROFILE_SPECIFIER: ""

targets:
  UnicornStoreWeb:
    type: application
    platform: iOS
    sources:
      - path: UnicornStoreWeb
    settings:
      base:
        INFOPLIST_FILE: UnicornStoreWeb/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.hellodajidali.unicornstoreweb
        PRODUCT_NAME: UnicornStoreWeb
    info:
      path: UnicornStoreWeb/Info.plist
